---
title: "Join the lab"
---

I am excited to hear from prospective technicians, students and postdoctoral scholars who are interested in marine community ecology. My lab will work in marine coastal ecosystems (e.g., coral reefs, rocky intertidal, seagrass), across multiple levels of biological taxa (e.g., sharks, fishes, corals, microbes), and integrate field observations, experiments and data synthesis to ask broad questions in community ecology.

**All members of the lab must be committed to promoting an inclusive, considerate, and collaborative culture. My lab is committed to creating an environment where scholars from diverse backgrounds get excited about research, grow as scientists, have equal opportunities, and feel included and valued.**  

### Prospective Graduate Students   
I will be accepting graduate students within the [School of Life Sciences](https://manoa.hawaii.edu/lifesciences/) through the [marine biology graduate program](https://mbiograd.manoa.hawaii.edu/) (November 15 deadline). If you are interested in joining my lab as a graduate student please email me and include: 

* A bief description of your research interests and how they overlap with my lab  
* Why you want to go to graduate school  
* A brief summary of your previous research experience  
* If you are eligible for the [NSF GRFP](https://www.nsfgrfp.org/). If you are eligible I will ask you to apply    
* Your CV    
<br>  

Graduate students at UH are paid through a combination of fellowships, RAships, and TAships. Please also look at PhD fellowship opportunities, with a few examples listed below.  

* [NSF GRFP](https://www.nsfgrfp.org/) and [examples of successful applications](https://docs.google.com/spreadsheets/u/1/d/1xoezGhbtcpg3BvNdag2F5dTQM-Xl2EELUgAfG1eUg0s/htmlview?urp=gmail_link)  
* [Nancy Foster Scholarship Program](https://fosterscholars.noaa.gov/)  
* [NSERC Fellowships](https://www.nserc-crsng.gc.ca/Students-Etudiants/index_eng.asp) (Canadian citizens)  
* [Ford Foundation Fellowship](https://www.nationalacademies.org/our-work/ford-foundation-dissertation-fellowships)  
* [Margaret A Davidson Graduate Fellowship](https://coast.noaa.gov/nerrs/research/davidson-fellowship.html) 
* [Database of fellowships](https://www.des.ucdavis.edu/faculty/baskett/links/academia.html#Grad)  
<br>  

### Prospective Post-doctoral Researchers   
If you are interested in joining my lab as a postdoc, please email me and tell me about your research interests and experience, attach your CV (with references), and attach 1-2 published or in-preparation manuscripts. I will post any grant funded opportunities here as funding becomes available. There are many fellowships to support independent post-docs and I am happy to work on proposals together (examples listed below).   

* [NSF Ocean Sciences PRF](https://new.nsf.gov/funding/opportunities/oce-prf-ocean-sciences-postdoctoral-research-fellowships)  
* [Smith Fellowship- Society for Conservation Biology](https://conbio.org/mini-sites/smith-fellows)  
* [Schmidt Science Fellows](https://schmidtsciencefellows.org/selection/)  
- [L'Oréal USA for Women in Science](https://www.loreal.com/en/usa/pages/group/fwis/)  
* [NOAA Climate and Global Change Postdoctoral Fellowship](https://cpo.noaa.gov/fellowships/)  
* [Database of fellowships in biology](https://docs.google.com/spreadsheets/u/1/d/1J2M_tQgoqV4ivpfEClh9qs9f2KQN2O1G3Jpda2aoHfQ/htmlview?pru=AAABflRz4WU*P-_JtdkwWzRc0-PlWGZSlQ#gid=0)  










